### ISSUE TITLE
_get_nested_attr returning None due to missing a return in the general case

### ISSUE THREAD

**Issue by andreykramer** [pytorch/functorch#1053]
I noticed that the `old_state` variable of  `make_functional.py::FunctionalModuleWithBuffers::forward` is always full of `None` elements. Digging a bit I saw that there is no return in the general case of [`_get_nested_attr`](https://github.com/pytorch/pytorch/blob/91b3cd0b5a7d297a82ca0f9068ea7f9ac1963ced/functorch/_src/make_functional.py#L43)

```def _get_nested_attr(obj: nn.Module, names: List[str]) -> None:
    if len(names) == 1:
        return getattr(obj, names[0])
    else:
        # No return here
        _get_nested_attr(getattr(obj, names[0]), names[1:])
```

So the outermost call is always returning `None` when `len(names) > 1`. If I'm right and this is a bug what implications does it have? For instance, the "Remove the loaded state on self.stateless_model" step surely wouldn't be doing what it's supposed to.

**Comment by zou3519** [comment]
Thanks for the catch, @andreykramer. This is indeed a bug.

From my reading of the code, make_functional/make_functional_with_buffers should still work as expected. The "Remove the loaded state on self.stateless_model" will still remove the loaded state, but instead of replacing a tensor with a meta tensor (a Tensor without storage), it'll replace a tensor with None.

It looks like the only implication is that if you directly access `self.stateless_model`, it will have some Nones where it should instead have meta tensors.
