### ISSUE TITLE
Calling VMap on Grad - Issues with Indexing

### ISSUE THREAD

**Issue by bchen0** [pytorch/functorch#381]
Hi,

When calling vmap on grad in order to compute per-sample gradients, it seems that indexing breaks. See below for an example - after x = self.net(x), x is a "GradTrackingTensor" whose shape should be (10, 5) but instead has shape 5 (and as a result the indexing later breaks)

This only seems to happen when calling vmap on grad. Calling grad by itself doesn't seem to break.

```
class TestNetwork(nn.Module):
  def __init__(self):
    super().__init__()
    self.net = nn.Linear(5, 5)
  def forward(self, x):
    x = self.net(x)
    print(x.shape)
    print("Should be (10,5)")
    x[:, 0] += 3
    return x

model = TestNetwork()
data = torch.randn(10,5)
targets = torch.randn(10, 5)

func_model, params = make_functional(model)

def compute_loss(params, data, targets):
    preds = func_model(params, data)
    return torch.mean((preds - targets) ** 2)

# This seems fine.
grad(compute_loss)(params, data, targets)

# This breaks
per_sample_grads = vmap(grad(compute_loss), (None, 0, 0))(params, data, targets)
```

Thanks,
Brian

**Comment by zou3519** [comment]
Thanks for the issue, @bchen0!

I'm assuming you have a batch size of 10 and want to compute a gradient per element in your batch (so, that is 10 gradients). If that is the case, then this is intentional - to compute per-sample-gradients with vmap, one should first write a function that computes gradients for a single example and then we can use vmap to lift it to computing a gradient per example.

More concretely, this means we need to modify compute_loss to handle `data` of shape (5,) and targets of shape (5,). The easiest way to do this without changing your model (which presumably assumes data and target have a batch dimension) is to add unsqueeze statements that add an additional dimension:

```
class TestNetwork(nn.Module):
  def __init__(self):
    super().__init__()
    self.net = nn.Linear(5, 5)
  def forward(self, x):
    x = self.net(x)
    print(x.shape)
    print("Should be (10,5)")
    x[:, 0] += 3
    return x

model = TestNetwork()
data = torch.randn(10,5)
targets = torch.randn(10, 5)

func_model, params = make_functional(model)

def compute_loss(params, data, targets):
    preds = func_model(params, data.unsqueeze(0))
    return torch.mean((preds - targets.unsqueeze(0)) ** 2)

# This seems fine.
grad(compute_loss)(params, data, targets)

# This breaks
per_sample_grads = vmap(grad(compute_loss), (None, 0, 0))(params, data, targets)
```

The following notebook goes through an example of this, if that helps: (https://github.com/pytorch/functorch/blob/main/notebooks/per_sample_grads.ipynb).

>  it seems that indexing breaks. See below for an example - after x = self.net(x), x is a "GradTrackingTensor" whose shape should be (10, 5) but instead has shape 5 (and as a result the indexing later breaks)

The semantics of vmap are that it "hides the dimension on tensors being vmapped". So inside of vmap, the tensor of shape (10, 5) looks like a tensor of shape (5,).

**Comment by bchen0** [comment]
Great, thanks for the explanation and link @zou3519! Quick follow up question - the code you posted leads to the following error for me:

RuntimeError: vmap: aten::copy_(self, *extra_args) is not possible because there exists a Tensor `other` in extra_args that has more elements than `self`. This happened due to `other` being vmapped over but `self` not being vmapped over at level 2. Please try to use out-of-place operators instead of aten::copy_. If said operator is being called inside the PyTorch framework, please file a bug report instead.

Do you have suggestions for performing operations on slices of a tensor in a out-of-place manner? An example closer to my use-case is shown below, where I want to combine the output of two NNs but only along certain slices. The real use-case is RealNVP.

```
class TestNetwork(nn.Module):
  def __init__(self):
    super().__init__()
    self.net1 = nn.Linear(5, 5)
    self.net2 = nn.Linear(5, 2)
  def forward(self, x):
    y = self.net1(x)
    z = self.net2(x)
    y[:, :2] *= z
    return y

model = TestNetwork()
data = torch.randn(10,5)
targets = torch.randn(10, 5)

func_model, params = make_functional(model)
def compute_loss(params, data, targets):
  preds = func_model(params, data.unsqueeze(0))
  return torch.mean((preds - targets.unsqueeze(0)) ** 2)

per_sample_grads = vmap(grad(compute_loss), (None, 0, 0))(params, data, targets)
```

**Comment by zou3519** [comment]
@bchen0 what version of functorch are you on? I think we fixed the bug you're referring to -- the code doesn't error for me on the functorch main branch

**Comment by bchen0** [comment]
@zou3519 Ah, thanks. I was working with the preview version but using the main branch works.

I do have one more related question about slicing - is there a difference between slicing using for instance x[:, :2] versus x[:, [0,1]] or x[:, torch.Tensor([0, 1]).to(dtype=int)]? The later two options lead to a shape mismatch error even though I would have thought these were equivalent.

(I can also open a new issue if that is preferred)

```
class TestNetwork(nn.Module):
  def __init__(self):
    super().__init__()
    self.net1 = nn.Linear(5, 5)
    self.net2 = nn.Linear(5, 2)
  def forward(self, x):
    y = self.net1(x)
    z = self.net2(x)
    # y[:, :2] *= z 
    y[:, torch.Tensor([0, 1]).to(dtype=int)] *= z # I run into an issue here even though using the line above instead seems to be okay
    # y[:, [0,1]] *= z # Same issue
    return y

model = TestNetwork()
data = torch.randn(10,5)
targets = torch.randn(10, 5)

func_model, params = make_functional(model)
def compute_loss(params, data, targets):
  preds = func_model(params, data.unsqueeze(0))
  return torch.mean((preds - targets.unsqueeze(0)) ** 2)

per_sample_grads = vmap(grad(compute_loss), (None, 0, 0))(params, data, targets)
```

**Comment by zou3519** [comment]
> x[:, :2] versus x[:, [0,1]] or x[:, torch.Tensor([0, 1]).to(dtype=int)]?

All three of those should work the same way. This is a bug on our side, thanks for catching it :).

**Comment by kshitij12345** [comment]
This issue is independent of calling `grad`.

It is due to interaction of core PyTorch and BatchedTensor on calling `setitem`.

Reproducer:
```python
from torch import nn
import torch
from functorch import vmap

def manual_vectorized():
  a = torch.zeros(2, 3)
  b = torch.ones(2, 2)

  a = a.unsqueeze(1)
  b = b.unsqueeze(1)

  # a[:, :, :2] = b
  a[:, :, [0, 1]] = b
  print(a)

manual_vectorized()

def fn(y, z):
  y = y.unsqueeze(0)
  z = z.unsqueeze(0)
  # y[:, :2] = z
  y[:, [0, 1]] = z
  return y

a = torch.zeros(2, 3)
b = torch.ones(2, 2)

print(vmap(fn, (0, 0))(a, b))

```

At `y[:, [0, 1]] = z`, we call `setitem`, we take the following path (we don't take this path for `y[:, :2] = z`)
```c++
IntArrayRef valueSizes = value.sizes();
IntArrayRef slicedValueSizes = at::indexing::slicePrefix1sSize(valueSizes);
torch::autograd::Variable valuesSliced;
if (!valueSizes.equals(slicedValueSizes)) {
  valuesSliced = value.view(slicedValueSizes);
} else {
  valuesSliced = value;
}
```
Link to the (Pytorch Code)[https://github.com/pytorch/pytorch/blob/b56ba296b1cb5d65a3fe2e33cc1d910481baa644/torch/csrc/autograd/python_variable_indexing.cpp#L438-L451]

For PyTorch, size of BatchedTensor `z (shape [2, 1, 2], batch_dim=0)` is `[1, 2]` as the batch dim is hidden, and hence `at::indexing::slicePrefix1sSize(valueSizes)` removes the leading `1` and passing the updated `z` with shape `[2, 2]`.

**Comment by zou3519** [comment]
It sounds like we have some fixing to do with PyTorch's indexing operations. Is that an accurate assessment?

**Comment by kshitij12345** [comment]
On digging a bit further, it is need to handle cases like the following
```python
import numpy as np
import torch

t = torch.zeros(2, 1, 3)
v = torch.ones(1, 2)

t_a = t.clone().numpy()
v_a = v.clone().numpy()

t_a[0 , 0, [0, 1]] = v_a
print(t_a)

t[0 , 0, [0, 1]] = v
print(t)
```

So I think the correct approach is actually to teach `index_put_` batching rule to understand this case.
