### ISSUE TITLE
[AOTAutoGrad] Questions about max-flow based algorithm for activation checkpointing

### ISSUE THREAD

**Issue by comaniac** [pytorch/functorch#385]
Hi PyTorch community,

Happy New Year!

I'm Cody from AWS and I attended the talk at TVMCon 2021 about PyTorch AOTAutoGrad given by @Chillee. After the talk, I had a short offline discussion about the checkpointing. Horace kindly pointed me to the PR (#344) that implements the checkpointing identification algorithm. Thanks again for the helpful information!

Since we are also working on checkpointing related features, my colleague Yuan (@zhouyuan1119) is evaluating the max-flow based algorithm and has some questions. Specifically, in this function:

https://github.com/pytorch/functorch/blob/f5f58188d4c0fad4925fb747bb35756b6469f5e3/functorch/_src/aot_autograd.py#L223

1. Why double the memory size for intermediate tensors? Is this like a penalty to adjust the max-flow results?
2. IIUC, the objective of this algorithm attempts to _minimize_ the memory footprint instead of _fitting_ to the given memory budget. We are wondering if this objective would introduce huge computation overheads when the original memory footprint is just slightly higher than the total memory budget?

Also cc @anijain2305

Thanks!

**Comment by Chillee** [comment]
Hi, thanks for your interest :)

1. The cost for an activation comes in 2 portions: the first is when the forwards pass writes it out to global memory, and the second is when the backwards pass reads it from global memory. For tensors that are already passed in as input, you don't need to write it out to global memory, since it already exists in global memory! Thus, the memory-bandwidth cost is merely the cost of reading it in the backwards pass.

2. This process minimizes the memory footprint subject to the constraints provided. If we limit ourselves only to bandwidth bound ops that can be fused, then this process should never introduce computation overheads, and in fact should always be more performant :) In practice, not all bandwidth bound ops can be fused and such, so it's not perfect, but if you're conservative about what operators you allow recomputation for, then we rarely reduce the runtime of the model, and when we do, it's only by <3-4%.

I'm writing up a note that I'll probably share more widely soon, that'll explain the approach more in depth. But feel free to ask more questions!

**Comment by comaniac** [comment]
Thanks for the prompt response! It makes sense now. Looking forward to the note soon :)

**Comment by Chillee** [comment]
@comaniac Note has been posted here with some results on various models: https://dev-discuss.pytorch.org/t/min-cut-optimal-recomputation-i-e-activation-checkpointing-with-aotautograd/467

**Comment by comaniac** [comment]
Thanks @Chillee! Will read it in detail soon.
I'm closing this issue first. For other questions we may have, we will directly discuss with you in the post :)
