### ISSUE TITLE
svd-related op regression in functorch

### ISSUE THREAD

**Issue by zou3519** [pytorch/functorch#428]
https://github.com/pytorch/pytorch/pull/69827 and https://github.com/pytorch/pytorch/pull/70253 caused svd-related tests in functorch to fail:
- https://app.circleci.com/pipelines/github/pytorch/functorch/1277/workflows/5aaf2c43-6c6a-4ab1-94f7-e0493b8049ff/jobs/7659

The main problem seems to be that the backward pass uses in-place operations that are incompatible with vmap (aka Composite Compliance problems). There are some other failures that seem to be because some other operations are not Composite Compliant but somehow these weren't a problem previously.

**Comment by Lezcano** [comment]
The problem is that `_svd_helper` was renamed to `_linalg_svd`. I thought this was allowed and not BC-breaking as this is a private function, but well.

Once that renaming is solved, another error will pop up, and it is that the backward now uses `at::allclose`, which is not supported by functorch (https://github.com/pytorch/functorch/issues/275). It is not clear to me whether we can implement the `allclose` functionality in a functorch compatible way, as `item<bool>()` is also forbidden. If we can't, perhaps we'll need to just comment out that check for now (which is a bit sad, as I think it's a somewhat important check and a nice new addition to SVD :( )

**Comment by zou3519** [comment]
The resolution of this issue is currently blocked on the pytorch nightlies being updated and the change being cherry-picked into the PyTorch 1.11 release branch.

**Comment by samdow** [comment]
Adding a note that `test_vjpvmap` started failing on `linalg.cond` and `linalg.svdvals`, [new xfails here](https://github.com/pytorch/functorch/commit/1011a35c7ebf83c5a6026407d7686edc88dc3c84). Wanted to mention here since they seem related

**Comment by Lezcano** [comment]
This issue I believe that should be closed. Now, about the new xfails, I think they may come from here:
https://github.com/pytorch/pytorch/pull/72309#discussion_r803045992
@soulitzer

**Comment by soulitzer** [comment]
I will create a PR to add back `isTensorSubclassLike(A)`, that should resolve `test_vjpvmap `failing for `linalg.svdvals`.

**Comment by zou3519** [comment]
> Another solution is just to stop decomposing at the Batched level for linalg.svdvals

This doesn't work if one composes vmap(grad(f)) -- grad(f) automatically does the decomposition, and then vmap sees the decomposed from of svdvals.

> The downside of adding isTensorSubclassLike is that we will always be computing singular vectors in functorch even when they are not needed, i.e. for vmap(f

Yeah, it's a tradeoff :/. We'll probably come up with something better than this in the future.

**Comment by Lezcano** [comment]
That was added back in https://github.com/pytorch/pytorch/pull/72811, which is merged, so this can probably be closed? I'll let @soulitzer confirm though.

**Comment by soulitzer** [comment]
Yep, that was merged.

**Comment by zou3519** [comment]
Awesome, looks like we're good here -- thanks again everyone (@Lezcano @vfdev-5  @soulitzer ) for working on fixing this
