### ISSUE TITLE
vmap fails for hessian of torch.trace

### ISSUE THREAD

**Issue by AlphaBetaGamma96** [pytorch/functorch#501]
Hello, 

I've been trying to vmap the hessian of torch.trace and it fails, however, calculating the jacobian is just fine. Here's a reproducible error,
```
import torch
from functorch import jacrev, vmap

matrix = torch.randn(2,4,4)
deriv1 = vmap(jacrev(torch.trace), in_dims=(0))(matrix)
print(deriv1)

deriv2 = vmap(jacrev(jacrev(torch.trace)), in_dims=(0))(matrix)
print(deriv2)
```

which results in  the following error,
```
RuntimeError: vmap: aten::index_fill_(self, *extra_args) is not possible because there exists a Tensor `other` in extra_args that has more elements than `self`. This happened due to `other` being vmapped over but `self` not being vmapped over at level 2. Please try to use out-of-place operators instead of aten::index_fill_. If said operator is being called inside the PyTorch framework, please file a bug report instead.
```

I assume this error just because pytorch calls an in-place error and it's not a fault with functorch's `jacrev` function? I only ask this because this works for `jacrev(jacfwd(torch.trace))`.

For example, 
```
import torch
from functorch import jacfwd, jacrev, vmap

matrix = torch.randn(2,4,4)
try:
    deriv1 = vmap(jacrev(torch.trace), in_dims=(0))(matrix)
    print("jacrev(torch.trace) passed")
except:
    print("jacrev(torch.trace) failed")

try:
    deriv2 = vmap(jacrev(jacrev(torch.trace)), in_dims=(0))(matrix)
    print("jacrev(jacrev(torch.trace)) passed")
except:
    print("jacrev(jacrev(torch.trace)) failed")

try:
    deriv3 = vmap(jacrev(jacfwd(torch.trace)), in_dims=(0))(matrix)
    print("jacrev(jacfwd(torch.trace)) passed")
except:
    print("jacrev(jacfwd(torch.trace)) failed")
```
returns,
```
jacrev(torch.trace) passed
jacrev(jacrev(torch.trace)) failed
jacrev(jacfwd(torch.trace)) passed
```
where the error is the same RunTimeError stated above! 

Thank you! :)

**Comment by zou3519** [comment]
We can definitely fix this, thanks for reporting @AlphaBetaGamma96

**Comment by vfdev-5** [comment]
Repro code without try/except gives the following warnings and error messages: 
```
/usr/local/lib/python3.8/dist-packages/torch/autograd/__init__.py:275: UserWarning: There is a performance drop because we have not yet implemented the batching rule for aten::trace_backward.

/usr/local/lib/python3.8/dist-packages/torch/autograd/__init__.py:275: UserWarning: There is a performance drop because we have not yet implemented the batching rule for aten::index_fill_.int_Tensor. 
Traceback (most recent call last): 
...
RuntimeError: vmap: aten::index_fill_(self, *extra_args) is not possible because there exists a Tensor `other` in extra_args that has more elements than `self`. This happened due to `other` being vmapped over but `self` not being vmapped over at level 2. Please try to use out-of-place operators instead of aten::index_fill_. If said operator is being called inside the PyTorch framework, please file a bug report instead.
```

If I understand correctly the problem here, is that `vmap(jacrev(...))` passes using the fallback vmap implementation and `vmap(jacrev(jacrev(...)))` fails inside pytorch native `trace_backward`.

We can implement a `trace_backward` decomposition simliar to what pytorch does without using `index_fill_` but `index_fill`, however we still would face `RuntimeError: aten::index_fill.int_Tensor hit the vmap fallback which is currently disabled` to fully enable the batch rule for `trace_backward`.

**Comment by zou3519** [comment]
@vfdev-5 one way to fix this is to use the `areAnyTensorSubclassLike` flag:
```
  auto grad_input = at::zeros(sizes[0] * sizes[1], grad.options());
  auto indices = at::arange(0, grad_input.numel(), sizes[1] + 1, grad.options().dtype(at::kLong));
  if (areAnyTensorSubclassLike({indices, grad}) {
    return grad_input.index_fill(0, indices, grad).view(sizes);
  }
  grad_input.index_fill_(0, indices, grad);
  return grad_input.view(sizes);
```
All functorch tensor subclasses return True for "areAnyTensorSubclassLike". The downside is that this slows down trace_backward a little for us even when we're not doing vmap over this but that is better than having it error out

**Comment by vfdev-5** [comment]
Thanks for the suggestion. This code we implement in functorch right, not in pytorch ?
I was also thinking to use `index_put_` (at least temporarily) which is better covered by functorch. Haven't yet tested everything... What do you think ?

**Comment by zou3519** [comment]
> Thanks for the suggestion. This code we implement in functorch right, not in pytorch ?

Sorry, to clarify, we have two options:
1. Make the above change in pytorch/pytorch
2. Register the following as a decomposition in https://github.com/pytorch/functorch/blob/main/functorch/csrc/PyTorchOperatorHacks.cpp. This means that whenever functorch encounters trace_backward, it will run whatever gets registered in https://github.com/pytorch/functorch/blob/main/functorch/csrc/PyTorchOperatorHacks.cpp

```
auto grad_input = at::zeros(sizes[0] * sizes[1], grad.options());
auto indices = at::arange(0, grad_input.numel(), sizes[1] + 1, grad.options().dtype(at::kLong));
return grad_input.index_fill(0, indices, grad).view(sizes);
```

Option 2 is the least intrusive and has the benefit that it'll work for PyTorch 1.11 (since the branch cut happened already) and future versions of PyTorch, so yes, we should probably do it in functorch.

For the long-term we probably want something like Option 1 in pytorch/pytorch.

> I was also thinking to use `index_put_` (at least temporarily) which is better covered by functorch. Haven't yet tested everything... What do you think ?

What do you mean by better covered?

**Comment by vfdev-5** [comment]
> What do you mean by better covered?

we can vmap and grad over `index_put`/`index_put_`

**Comment by zou3519** [comment]
Gotcha. I'm not sure what the semantics of index_put vs index_fill are -- if they're pretty similar then we can substitute index_put. In the long run we'll want a batching rule for index_fill

**Comment by zou3519** [comment]
@AlphaBetaGamma96  this should be fixed on the main branch with https://github.com/pytorch/functorch/pull/527, please let us know if the problem still persists.
