### ISSUE TITLE
How to perform jvps and not vjps?

### ISSUE THREAD

**Issue by trenta3** [pytorch/functorch#67]
Hi! Thanks for the working prototype, it would be a great addition to pytorch!

I'm currently using pytorch for research purposes, and I would like to implicitly compute jacobian-vector products (i.e. where the given vectors should multiply the "inputs" and not the "outputs" of the transformation).

Is there a `jvp` function? Is there a workaround?

**Comment by trenta3** [comment]
I have possibly found a workaround to simulate `jvp` using `vjp`.

```python3
from functorch import vjp

def jvp(f, i):
    """
    Implementation of jvp using vjp.

    The jacobian of the vjp function is J^T.
    So to obtain Jv we have to use the vjp of the vjp function.
    """
    ans, f_vjp = vjp(f, i)
    _, f_vjp_vjp = vjp(f_vjp, torch.zeros_like(ans))
    return ans, lambda i: f_vjp_vjp((i,))[0]
```

It seems to be of acceptable performance, does torch optimizes such a computation?

**Comment by Chillee** [comment]
@trenta3 Sorry for missing this - I think it was since it was closed very quickly :P

I don't think there's anything wrong with computing jvp using 2 vjps. The primary issue, from my understanding, is that this will take 2 function evaluations compared to the 1 from a proper jvp implementation. Of course, this is still way better than calling autograd.grad once per function output.

The "proper" way to do this is to use PyTorch's (experimental) forward-mode AD. You can see the tracking issue here: https://github.com/facebookresearch/functorch/issues/20, and try it out with `functorch.experimental.jvp`. Be warned that Pytorch's forward-mode AD is not mature yet, and you may run into forward-mode formulas that are missing.

**Comment by trenta3** [comment]
@Chillee Thanks for the reply, very useful information indeed, especially the fact that by using two vjps I only loose a 2x factor.
I will subscribe to the other issue to see when the jvp function is mature enough!
Thank you for this great repository, that is essential for my research!

**Comment by trenta3** [comment]
I will now close this issue as the `jvp` function is readily available.
Thank you very much for the great work!

**Comment by zou3519** [comment]
Please let us know if you run into any other issues or have more feedback!
